### PR TITLE
python3: slots do not work for class attribute

### LINKED ISSUE #12: Crash with Python 3.5
Reproducible with Python 3.4, too. But no issue in Python 2.

Description of problem: Crashes at launch.
Version-Release number of selected component (if applicable): apx-0.1-7.fc24
How reproducible: Start apx

Actual results:
```
  File "/usr/bin/apx", line 26, in <module>
    from apx.lib import graphics
  File "/usr/lib/python3.5/site-packages/apx/lib/graphics.py", line 185, in <module>
    class Graphics(object):
ValueError: 'colors' in __slots__ conflicts with class variable
```

Expected results: Run.

### PR DESCRIPTION
**Pull request by rapgro**
fixes #12

### CODE REVIEW

**Comment by tbaugis** [comment]
@elbenfreund - would you mind moving the ownership of apx to @tstriker ? (it's my new github account i'm transferring to)

**Comment by elbenfreund** [comment]
@tbaugis 
absolutly not. I was about to write an email concerning apx ... :)

**Comment by tstriker** [comment]
thanks @rapgro for the pull request and @elbenfreund for the transfer!

**Comment by elbenfreund** [comment]
You're welcome. shall I do the same for ``hamster-graphics`` aka ``experiments``?

**Comment by tstriker** [comment]
i guess graphics won't be maintained either, so sure!

**Comment by elbenfreund** [comment]
I think you ``graphics`` is great and certainly took a lot of work. I personally do not feel competent/interested enough in widget/Gtk development to dive into this in the foreseeable future so it is indeed unlikely to be well maintained as part of project hamster. And whist I think it cool and allows for some fancy stuff, I will try to avoid using it for the hamster rewrite as long as it is untested and undocumented.

One thing I wondered was if it would be possible to rewrite some of its functionality more closely related to Gtk core widgets by subclassing them and really just add some eyecandy on top of them.
But as I said, this would still need some investigation and work, so its unlikely to happen anytime soon.

With this being said, I think it would be great to transfer it to you now and work with you on this in the future as an independent widget library than a strict part of hamster.

**Pull request merged**
